// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dqamveraqvxivjhxtuha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxYW12ZXJhcXZ4aXZqaHh0dWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3ODUxMzMsImV4cCI6MjA4OTM2MTEzM30.Tvo6_jGcP5uJk0_b1f__SJqP1pMtUKGajw-HbGUq5E8";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);